server:
  port: 8001
  servlet:
    context-path: /mswl/ac
spring:
  application:
    name: mswl-ac
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.40.91.82:3306/mswl?allowMultiQueries=true&characterEncoding=utf8&useSSL=false&useAffectedRows=true&serverTimezone=UTC
    username: root
    password: bEQt23UPOwwRXNkC
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    call-setters-on-nulls: true