server:
  port: 8003
  servlet:
    context-path: /gramtu/mini
spring:
  application:
    name: gratu-mini
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.40.91.82:3306/mswl?allowMultiQueries=true&characterEncoding=utf8&useSSL=false&useAffectedRows=true&serverTimezone=UTC
    username: root
    password: bEQt23UPOwwRXNkC
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 500MB
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
fdfs:
  # 读取超时
  so-timeout: 1501
  # 连接超时
  connect-timeout: 601
  tracker-list:
    - 121.40.91.82:22122
#logging:
#  file: /home/gramtu/logs/turnin-ac.log